name: Auto Click Streamlit App

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时1次

jobs:
  run-click-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run the click script
        env:
          STREAMLIT_COOKIE: ${{ secrets.STREAMLIT_COOKIE }}
          PROJECT_URL: ${{ secrets.PROJECT_URL }}
        run: python keep-streamit.py
